from . import bestChoiceKb
from . import bestChoiceKb3
from . import langKeyboard
from . import bestChoiceKb2
from . import clientsChat
from . import photoKb
from . import textKb
from . import divider
from . import choosePhoto
from . import disagreementKb
from . import fwdBwdForFirstText
from . import fwdBwdForSecondText
from . import fwdBwdForThirdText
from . import fwdBwdForFourthText